### ISSUE TITLE
Merge conflict in the gitMergeOops branch

### ISSUE THREAD

**Issue by SeanGallen** [SeanGallen/githubfiasco#2]
Please fix the merge conflict by deleting the stuff in the master index.js file.

**Comment by morrme** [comment]
This requires write access to the files.

**Comment by SeanGallen** [comment]
Hi @morrme, 
Thank you for reaching out.  I created this repo with a friend to play around with github.  I was going to have him create a pull request before I opened up access.  I never expected a response from anyone else but I do appreciate it.  You are welcome to join if you find it interesting.  There is also an interesting repo at https://github.com/grayghostvisuals/practice-git that might be cool too.

**Comment by morrme** [comment]
@SeanGallen Ah! I see! Sorry about that. Thanks for the explanation, and the pointer to the other repo! It's cool that these things exist!

**Comment by SeanGallen** [comment]
I agree and thank you again.
